spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev
  mvc:
    hiddenmethod:
      filter:
        enabled: true
#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
