spring:
  datasource:
    url: jdbc:mysql://8.129.222.219:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    root: warn
    com.wch.blog: info
  file:
    name: log/blog-pro.log

server:
  port: 8081
